AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template: S3 Bucket'

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'cloudformation-s3-091771-bucket'
      AccessControl: 'Private'
      VersioningConfiguration:
        Status: 'Enabled'
      Tags:
        - Key: 'Environment'
          Value: 'Production'
      LifecyleConfiguration:
        Rules:
          - Id: 'ExpireOldObjects'
            Status: 'Enabled'
            Prefix: ""
            Transitions:
              - StorageClass: 'STANDARD_IA'
                TransitionInDays: 30
              - StorageClass: 'GLACIER'
                TransitionInDays: 90  
                StorageClass: 'DEEP_ARCHIVE'
                TransitionInDays: 180
      publicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
Outputs:
  S3BucketName:
    Description: 'Name of the S3 Bucket'
    Value: !Ref MyS3Bucket            
      